name: Build 21.02rc1 for r4s

on:
  push:
    branches: [ 21.02rc1 ]
  pull_request:
    branches: [ 21.02rc1 ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
